version: "3.5"
services:
  postgres:
    container_name: postgres10
    # image: postgres:10.23-alpine3.16
    platform: linux/x86_64
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: fbrcode/postgres10:latest
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
      # - ./sql:/sql
      # - ./sql/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      # - ./tests:/tests
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    networks:
      default:
        aliases:
          - postgres

volumes:
  postgres-volume:
networks:
  default:
    name: my-net
